# Generated by Django 3.1.7 on 2021-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20210412_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='AGE',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='APPROACHES',
            new_name='approaches',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='CHASING',
            new_name='chasing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='CLIMBING',
            new_name='climbing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='EATING',
            new_name='eating',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='FORAGING',
            new_name='foraging',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='INDIFFERENT',
            new_name='indifferent',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='KUKS',
            new_name='kuks',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='LATITUDE',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='LOCATION',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='LONGITUDE',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='MOANS',
            new_name='moans',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='OTHER_ACTIVITIES',
            new_name='other_activities',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='PRIMARY_FUR_COLOR',
            new_name='primary_fur_color',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='QUAAS',
            new_name='quaas',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='RUNNING',
            new_name='running',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='RUNS_FROM',
            new_name='runs_from',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='SHIFT',
            new_name='shift',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='SPECIFIC_LOCATION',
            new_name='specific_location',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='TAIL_FLAGS',
            new_name='tail_flags',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='TAIL_TWITCHES',
            new_name='tail_twitches',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='DATE',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
